version: 2.1

jobs:
  dapp_test:
    docker:
      - image: bakii0499/dapptools:0.48.0-solc-0.8.7
    steps:
      - run:
          name: Checkout contract-test-suite
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:maple-labs/contract-test-suite.git .
            git checkout $CIRCLE_BRANCH
            mkdir cache
            cd cache
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:maple-labs/cts-cache.git
      - run:
          name: Build and test contracts
          command: |
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --init --recursive
            ./test.sh -c ./config/ci.json -r 10
          no_output_timeout: 60m
workflows:
  version: 2
  test_all:
    jobs:
      - dapp_test:
          context: seth
